#!/bin/bash

. $HOME/dotfiles/scripts/utils/colors

# Set source and target directories
powerline_fonts_dir=$HOME/dotfiles/powerline/fonts

find_command="find \"$powerline_fonts_dir\" \( -name '*.[o,t]tf' -or -name '*.pcf.gz' \) -type f -print0"

if [[ `uname` == 'Darwin' ]]; then
  # MacOS
  font_dir="$HOME/Library/Fonts"
else
  # Linux
  font_dir="$HOME/.fonts"
  sudo mkdir -p $font_dir
fi

# Copy all fonts to user fonts directory
eval $find_command | xargs -0 -I % sudo cp "%" "$font_dir/"

# Reset font cache on Linux
if [[ -n `which fc-cache` ]]; then
  fc-cache -f $font_dir
fi

echo -e "\n${green}All Powerline fonts installed to $font_dir.${nc}"
