#!/bin/bash

. $HOME/dotfiles/scripts/utils/has_command

if ! has_command fortune; then
  if has_command brew; then
    brew install fortune
  elif has_command yum; then
    cd /tmp
    wget http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    rpm -ivh epel-release-6-8.noarch.rpm
    sudo rm -rf epel*
    sudo yum install fortune-mod.x86_64
  elif has_command apt-get; then
    sudo apt-get install fortune
  fi
fi
