#!/bin/bash

. $HOME/dotfiles/scripts/utils/has_command

if has_command brew; then
  brew install fortune
elif has_command yum; then
  sudo yum install fortune
elif has_command apt-get; then
  sudo apt-get install fortune
fi
