#!/bin/bash

. $HOME/dotfiles/scripts/utils/colors

install_dir=/usr/local/bin
python_version=$(python --version 2>&1)
required_version=2.7

case "$python_version" in
    *" $required_version"*)
      echo -e "\n${green}$python_version is already installed.${nc}"
      # correct python version. no need to do anything
    ;;

    *)
      cd /tmp
      wget https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
      tar xfv Python-2.7.10.tgz
      cd Python-2.7.10
      ./configure --prefix=$install_dir
      sudo make && sudo make install
      cd /tmp && sudo rm -rf Python-2.7.10*

      echo -e "\n${green}$python_version was successfully installed.${nc}"
    ;;
esac
