#!/bin/bash

. $HOME/dotfiles/scripts/utils/colors

current_dir=$(pwd)

# install huge vim with python support
if ! vim --version | grep +python &>/dev/null; then
  cd /tmp
  git clone https://github.com/vim/vim.git
  cd vim

  ./configure \
    --with-features=huge \
    --enable-pythoninterp \
    --with-python-config-dir=/usr/local/lib/python2.7/config \
    --enable-rubyinterp

  sudo make && sudo make install
  cd /tmp && sudo rm -rf vim
  cd $current_dir

  echo -e "\n${green}Vim74 is successfully installed.${nc}"
fi
