#!/bin/bash

set -euo pipefail

XDG_CONFIG_HOME="$HOME/.config"
Log=/tmp/dotfiles.log

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "platform is mac osx. Installing.."
  ./usr/local/bin/osx-bootstrap  | tee -a $Log
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo "platform is arch. Installing.."
  ./usr/local/bin/arch-bootstrap | tee -a $Log 
fi

nvim_dir=$XDG_CONFIG_HOME/nvim
if [ ! -d $nvim_dir ]; then 
  echo "setting up nvchad base.." | tee -a $Log 
  mkdir -p $nvim_dir
  git clone https://github.com/NvChad/NvChad $nvim_dir --depth 1 | tee -a $Log
fi

echo "setting up dotfiles.." | tee -a $Log 
sudo rm -f ~/.zshrc /etc/locale.conf
stow --target=$HOME home 
stow --target=$XDG_CONFIG_HOME config
sudo stow --target=/etc etc


if [[ "$OSTYPE" == "darwin"* ]]; then
  sudo stow --target=/usr/local/bin --dir=usr/local bin
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  sudo stow --target=/usr usr 
  
  sudo locale-gen | tee -a $Log

  echo "setting email with mutt"
  systemctl --user start mailsync
  systemctl --user enable mailsync.timer
fi

echo "installing tmux plugins" | tee -a $Log
if [ ! -d $HOME/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi
$HOME/.tmux/plugins/tpm/bin/install_plugins

echo "installing node lts" | tee -a $Log
fnm install --lts
fnm default lts-latest
[ ! -f ~/.node-version ] && echo "lts-latest" > ~/.node-version

echo "installing lf"
env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest

echo "logging in to github"
github-login

if [[ $SHELL != *"zsh" ]]; then
  chsh -s $(which zsh)
fi

echo "all done!!"

exec zsh
