#!/bin/bash
set -euo pipefail

XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_CACHE_HOME="$HOME/.cache"

current_dir=$(pwd)

log=/tmp/dotfiles.log

remove_package() {
  if yay -Qs $1 &>> /dev/null; then
    yay -R --noconfirm $1
  fi
}

install_package() {
  if yay -Q $1 &>> /dev/null; then
   echo "$1 is already installed"
  else
    yay -S $1 --noconfirm 
  fi
}

# █▀█ ▄▀█ █▀▀ █▄▀ ▄▀█ █▀▀ █▀▀ █▀
# █▀▀ █▀█ █▄▄ █░█ █▀█ █▄█ ██▄ ▄█

packages=(
  cmake
  glibc
  openssl
  zsh
  bash
  curl
  unzip
  tar
  jq
  make
  stow
  tmux
  less
  pass
  pass-otp
  gnupg
  pam-gnupg
  mandb
  neofetch
  aws-cli
  aws-vault
  github-cli
  lua
  rustup
  neovim
  starship
  btop
  fnm
  ttf-jetbrains-mono-nerd
  zoxide
  bat
  git-delta
  fuse
  mergerfs
)


# █ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░   █▄█ ▄▀█ █▄█
# █ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄   ░█░ █▀█ ░█░

if [ ! -f /sbin/yay ]; then
  echo "installing yay"
  cd /tmp
  sudo pacman -S --needed git base-devel --noconfirm
  [ ! -d /tmp/yay ] && git clone https://aur.archlinux.org/yay.git 
  cd yay && makepkg -si --noconfirm
  cd $current_dir
fi


# █ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░   █▀█ ▄▀█ █▀▀ █▄▀ ▄▀█ █▀▀ █▀▀ █▀
# █ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄   █▀▀ █▀█ █▄▄ █░█ █▀█ █▄█ ██▄ ▄█

yay -Suy --noconfirm

echo "installing packages"
for package in ${packages[@]}; do
  install_package $package
done

echo "🎉  completed arch bootstrap"

# █▀ █▀▀ ▀█▀ █░█ █▀█   █▀▄ █▀█ ▀█▀ █▀▀ █ █░░ █▀▀ █▀
# ▄█ ██▄ ░█░ █▄█ █▀▀   █▄▀ █▄█ ░█░ █▀░ █ █▄▄ ██▄ ▄█

echo "setting up dotfiles.." | tee -a $log 
sudo rm -rf $HOME/.zshrc /etc/locale.conf /etc/locale.gen \
  /etc/pam.d/login /etc/pam.d/system-local-login /etc/zsh/zshenv 

mkdir -p $HOME/.local

stow --target=$HOME home 
stow --target=$XDG_CONFIG_HOME config
stow --target=$HOME/.local local
sudo stow --target=/etc etc

sudo locale-gen | tee -a $log


# ▀█▀ █▀▄▀█ █░█ ▀▄▀   █▀█ █░░ █░█ █▀▀ █ █▄░█ █▀
# ░█░ █░▀░█ █▄█ █░█   █▀▀ █▄▄ █▄█ █▄█ █ █░▀█ ▄█

echo "installing tmux plugins" | tee -a $log
if [ ! -d $XDG_CONFIG_HOME/tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm $XDG_CONFIG_HOME/tmux/plugins/tpm
fi
$XDG_CONFIG_HOME/tmux/plugins/tpm/bin/install_plugins


# █▀▄▀█ █▀█ █▀█ █▀▀   █▀█ ▄▀█ █▀▀ █▄▀ ▄▀█ █▀▀ █▀▀ █▀
# █░▀░█ █▄█ █▀▄ ██▄   █▀▀ █▀█ █▄▄ █░█ █▀█ █▄█ ██▄ ▄█

echo "installing default rust.."
rustup default stable
rustup component add rust-analyzer

echo "installing node lts" | tee -a $log
fnm install --lts
fnm default lts-latest
[ ! -f ~/.node-version ] && echo "lts-latest" > ~/.node-version

echo "logging in to github" | tee -a $log
$HOME/dotfiles/local/bin/github-login

if [[ $SHELL != *"zsh" ]]; then
  command -v zsh | sudo tee -a /etc/shells
  chsh -s $(which zsh) $(whoami)
fi

echo "all done!!"

exec zsh
