set runtimepath+=~/dotfiles/vim

" Load the plugins
if filereadable(expand("~/dotfiles/vim/plugins.vim"))
  source ~/dotfiles/vim/plugins.vim
endif


" Source local scripts/plugins
for filePath in split(globpath('~/dotfiles/vim/vimrcs', '*.vim'), '\n')
  execute 'source' filePath
endfor

" load custom config if available
if !empty(glob("$HOME/.my_vimrc"))
  execute 'source $HOME/.my_vimrc'
endif

colorscheme ir_black


