set runtimepath+=$HOME/dotfiles/vim

" Load the plugins
if filereadable(expand("$HOME/dotfiles/vim/plugins.vim"))
  source $HOME/dotfiles/vim/plugins.vim
endif

" Source vimrcs
for filePath in split(globpath('$HOME/dotfiles/vim/vimrcs', '*.vim'), '\n')
  execute 'source' filePath
endfor

" Source plugin configs
for filePath in split(globpath('$HOME/dotfiles/vim/configs', '*.vim'), '\n')
  execute 'source' filePath
endfor

" load custom config if available
if !empty(glob("$HOME/.my_vimrc"))
  execute 'source $HOME/.my_vimrc'
endif



