import:
   - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
     
env:
  TERM: xterm-256color

window:
  decorations: 'none'
  startup_mode: SimpleFullScreen

font:
  normal:
    family: FantasqueSansM Nerd Font 
    style: Regular

  bold:
    family: FantasqueSansM Nerd Font
    style: Bold

  italic:
    family: FantasqueSansM Nerd Font 
    style: Italic

  bold_italic:
    family: FantasqueSansM Nerd Font
    style: Bold Italic

  offset:
    x: 0 # letter spacing
    y: 6 # line height

  glyph_offset:
    x: 0
    y: 0

  size: 16

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

cursor:
  style: Block
  unfocused_hollow: true

# open tmux at start
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
      
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

key_bindings:
  - { key: W,        mods: Command,       action: None                        }
  - { key: Return,        mods: Command,  action: ToggleFullscreen            }
