env:
  TERM: alacritty

window:
  decorations: 'none'
  startup_mode: SimpleFullScreen

font:
  normal:
    family: FantasqueSansM Nerd Font Mono
    style: Regular

  bold:
    family: FantasqueSansM Nerd Font Mono
    style: Bold

  italic:
    family: FantasqueSansM Nerd Font Mono
    style: Italic

  bold_italic:
    family: FantasqueSansM Nerd Font Mono
    style: Bold Italic

  offset:
    x: 0 # letter spacing
    y: 6 # line height

  glyph_offset:
    x: 0
    y: 4

  size: 16

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

cursor:
  style: Block
  unfocused_hollow: true

# open tmux at start
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
      
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

key_bindings:
  - { key: W,        mods: Command,       action: None                        }
  - { key: Return,        mods: Command,  action: ToggleFullscreen            }

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '#fb4934'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '#fb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'
