#!/bin/bash

set -euo pipefail

current_dir=$(pwd)
ARCH=$(uname -m)

remove_package() {
  if yay -Qs $1 &>> /dev/null; then
    yay -R --noconfirm $1
  fi
}

install_package() {
  if yay -Q $1 &>> /dev/null; then
   echo "$1 is already installed"
  else
    yay -S $1 --noconfirm
  fi
}


# █▀█ ▄▀█ █▀▀ █▄▀ ▄▀█ █▀▀ █▀▀ █▀
# █▀▀ █▀█ █▄▄ █░█ █▀█ █▄█ ██▄ ▄█

packages=(

  # ▄▀█ █░█ █▀▄ █ █▀█
  # █▀█ █▄█ █▄▀ █ █▄█

  sof-firmware
  pipewire
  wireplumber
  pipewire-pulse
  pipewire-alsa
  pipewire-audio
  pipewire-jack
  pavucontrol
  pamixer
  alsa-utils

  # █░█ ▀█▀ █ █░░ █ ▀█▀ █ █▀▀ █▀
  # █▄█ ░█░ █ █▄▄ █ ░█░ █ ██▄ ▄█

  snapd
  blueman
  network-manager-applet
  file-roller
  swappy
  grim
  slurp
  cliphist
  wl-clipboard
  socat
  ffmpeg
  imv                       # image viewer
  fprintd                   # finterprint support
  udiskie                   # auto mount usb drives


  # █░█ █▄█ █▀█ █▀█ █░░ ▄▀█ █▄░█ █▀▄
  # █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▀█ █░▀█ █▄▀

  hyprlang
  hyprland
  hypridle
  hyprlock
  hyprpaper
  hyprsunset
  hyprpolkitagent
  hyprpicker-git
  waybar
  xdg-desktop-portal-hyprland
  xdg-desktop-portal-gtk # required as hyprland doesnt implement file picker
  xwaylandvideobridge-git
  gtk3
  gnome-keyring
  seahorse
  dunst
  qt5-wayland
  qt6-wayland
  rofi-lbonn-wayland-git
  wlogout
  gvfs


  # ▀█▀ █░█ █▀▀ █▀▄▀█ █▀▀
  # ░█░ █▀█ ██▄ █░▀░█ ██▄

  papirus-icon-theme
  xfce4-settings
  nwg-look-bin
  kvantum
  qt5ct
  qt6ct
  qt5-svg
  qt5-quickcontrols2
  qt5-graphicaleffects
  catppuccin-gtk-theme-mocha


  # █▀▄ █▀▀ █░█ █▀▀ █░░ █▀█ █▀█ █▀▄▀█ █▀▀ █▄░█ ▀█▀
  # █▄▀ ██▄ ▀▄▀ ██▄ █▄▄ █▄█ █▀▀ █░▀░█ ██▄ █░▀█ ░█░

  go
  rustup
  lldb
  aws-cli-v2
  github-cli
  lua
  tmux-git
  neovim
  yarn
  fnm
  pnpm
  npm
  python-requests
  pacman-contrib
  starship


  # █▀█ █▀▀ █▀▀ █ █▀▀ █▀▀
  # █▄█ █▀░ █▀░ █ █▄▄ ██▄

  # neomutt
  # ikhal
  # abook
  # msmtp
  # davmail
  # mailctl-bin
  # vdirsyncer
  # isync
  # notmuch
  # pandoc
  # lynx
  # glow
  # cyrus-sasl-xoauth2-git
  # python-aiohttp-oauthlib
  # urlscan
  betterbird-bin


  # ▄▀█ █▀█ █▀█ █░░ █ █▀▀ ▄▀█ ▀█▀ █ █▀█ █▄░█ █▀
  # █▀█ █▀▀ █▀▀ █▄▄ █ █▄▄ █▀█ ░█░ █ █▄█ █░▀█ ▄█

  btop
  mpv                     # media player
  rclone                  # used for gdrive sync
  aws-vault
  kitty
  docker
  docker-compose
  postman-bin
  thunar                  # GUI file explorer
  thunar-archive-plugin
  slack-desktop
  brave-bin
  1password
  1password-cli
  nnn                    # CLI file explorer
  zathura                # pdf viewer
  zathura-pdf-mupdf      # pdf viewer

  # discord


  # █▀▀ █▀█ █▄░█ ▀█▀ █▀
  # █▀░ █▄█ █░▀█ ░█░ ▄█

  ttf-fantasque-nerd
  ttf-jetbrains-mono-nerd
  ttf-nato-sans-nerd
  noto-fonts-emoji
  noto-fonts
)

# █ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░   █▀█ ▄▀█ █▀▀ █▄▀ ▄▀█ █▀▀ █▀▀ █▀
# █ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄   █▀▀ █▀█ █▄▄ █░█ █▀█ █▄█ ██▄ ▄█

yay -Suy --noconfirm

echo "installing packages"
for package in ${packages[@]}; do
  install_package $package
done

systemctl --user enable --now hyprpolkitagent.service

echo "🎉  completed arch bootstrap"


# █▀▀ █░░ █▀▀ ▄▀█ █▄░█ █░█ █▀█
# █▄▄ █▄▄ ██▄ █▀█ █░▀█ █▄█ █▀▀

echo -e "Cleaning out conflicting xdg portals..."

remove_package xdg-desktop-portal-gnome
remove_package xdg-desktop-portal-gtk
