#!/bin/bash
set -euo pipefail

XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_CACHE_HOME="$HOME/.cache"

log=/tmp/dotfiles.log

current_dir=$(pwd)
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $script_dir

# █ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░
# █ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "platform is mac osx. Installing.."
  ./osx-bootstrap  | tee -a $log
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo "platform is arch. Installing.."
  ./arch-base-bootstrap | tee -a $log
  ./arch-bootstrap | tee -a $log
fi

update-desktop-database $HOME/.local/share/applications

# █▀▀ █░░ █▀▀ █▀▀ ▀█▀ █▀█ █▀█ █▄░█   █▀▀ █▀█ █▄░█ █▀▀ █ █▀▀
# ██▄ █▄▄ ██▄ █▄▄ ░█░ █▀▄ █▄█ █░▀█   █▄▄ █▄█ █░▀█ █▀░ █ █▄█

electron_versions=(24 25)
for version in ${electron_versions[@]}; do
  file=$XDG_CONFIG_HOME/electron$version-flags.conf
  [ ! -f $file ] && ln -s $HOME/dotfiles/config/electron-flags.conf $file
done


if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  sudo locale-gen | tee -a $log

  # echo "starting mutt service" | tee -a $log
  # systemctl --user enable --now mailsync.timer

  # echo "starting vdirsyncer service" | tee -a $log
  # systemctl --user enable --now vdirsyncer.timer

  # echo "starting davmail service" | tee -a $log
  # systemctl --user enable --now davmail@subash.adhikari@memories.net

  # echo "configuring mailctl" | tee -a $log
  # export memories_client_id=$(pass memories/outlook/client_id)
  # export memories_client_secret=$(pass memories/outlook/client_secret)
  # mkdir -p $HOME/.local/var/mailctl $HOME/.local/var/msmtp
  # envsubst <"$HOME/dotfiles/config/mailctl/services-temp" >"$XDG_CONFIG_HOME/mailctl/services.yaml"
  # envsubst <"$HOME/dotfiles/config/mailctl/config-temp" >"$XDG_CONFIG_HOME/mailctl/config.yaml"

  echo "setting gdrive with rclone" | tee -a $log
  [ ! -d $HOME/gdrive ] && mkdir $HOME/gdrive
  [ ! -d /opt/rclone/logs ] && sudo mkdir -p /opt/rclone/logs
  sudo chmod -R 777 /opt/rclone/logs
  systemctl --user enable rclone
  systemctl --user start rclone &

  echo "setting up battery alerts"
  systemctl --user enable --now battery-alert.timer
fi


./post-install

cd $current_dir
echo "all done!!"
