#!/bin/bash

. ./scripts/colors

# install huge vim with python support
if ! vim --version | grep +python &>/dev/null; then
  cd /tmp
  wget ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2
  tar xfv vim-7.4.tar.bz2
  cd vim74

  ./configure \
    --with-features=huge \
    --enable-pythoninterp \
    --with-python-config-dir=/usr/local/lib/python2.7/config \
    --enable-rubyinterp

  sudo make clean && sudo make && sudo make install
  cd /tmp && rm sudo -rf vim74 vim-7.4.tar.bz2

  echo -e "\n${green}Vim74 is successfully installed.${nc}"
fi
