#!/bin/bash

. $HOME/dotfiles/scripts/utils/backup_dir
. $HOME/dotfiles/scripts/utils/colors

declare -A dotfiles

# list of dotfiles
dotfiles[zshrc]=zsh/zshrc
dotfiles[vimrc]=vim/vimrc
dotfiles[tmux.conf]=tmux/tmux.conf
dotfiles[gitconfig]=git/gitconfig

restart_required=false

# load each dotfiles
for i in "${!dotfiles[@]}"; do
  config=~/.$i
  dotfile=${dotfiles[$i]}

  if ! diff $config $dotfile &>/dev/null; then

    if [ -f $config ]; then
      mv $config "$BACKUP_DIR" 2>/dev/null
      echo -e "\n${yellow}$config is backed up in "$BACKUP_DIR".${nc}"
    fi

    ln -s $HOME/dotfiles/$dotfile $config
    echo -e "\n${green}$dotfile is successfully linked.${nc}"

    if [ "$i" == "zshrc" ]; then export restart_required=true; fi
  fi
done

