#!/bin/bash

set -euo pipefail

# install homebrew if not already installed
if ! type "brew" > /dev/null 2>&1; then
  echo "installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

echo "updating brew..."
brew update

# brew taps
# taps=(
#   heroku/brew
# )

# echo "tapping brews..."
# brew tap ${taps[@]}

# install binaries
binaries=(
 cmake
 openssl
 zsh
 bash
 ctags
 git
 gh # github cli
 go
 lua
 readline
 tmux
 nvim
 gradle
 yarn
 pnpm
 reattach-to-user-namespace
 openvpn
 svn
 fnm
 fzf
 direnv
 awscli
 ripgrep
 aws-vault
 hammerspoon
 jq # lightweight json parser
 koekeishiya/formulae/yabai # MacOS window manager
 stow
 starship
 neomutt
 zoxide
)

echo "installing binaries..."
brew install ${binaries[@]}

# install applications
apps=(
  kitty
  alacritty
  docker
  brave-browser
  1password
  1password/tap/1password-cli
  vlc
  google-drive
  discord
  slack
  microsoft-teams
  postman
  Karabiner-elements # keyboard manager
)

echo "installing applications..."
brew install ${apps[@]}

# configure fzf bindings
$(brew --prefix)/opt/fzf/install --all

echo "tapping cask fonts"
brew tap homebrew/cask-fonts

# install fonts
fonts=(
  font-clear-sans
  font-roboto
  font-hack-nerd-font
  font-fantasque-sans-mono-nerd-font
)

echo "installing fonts..."
brew install ${fonts[@]}

echo "installing powerline fonts..."
if [ -f "$HOME/Library/Fonts/Inconsolata for Powerline.otf" ]; then
  echo "powerline is fonts already installed."
else
  currentdir=$(pwd)
  cd /tmp
  git clone https://github.com/powerline/fonts.git && cd fonts
  chmod +x install.sh
  ./install.sh
  cd $currentdir
fi

# install rust and rust analyzer
if ! type "rustup" > /dev/null 2>&1; then
  echo "installing rust and rust analyzer"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
else
  echo "rustup is ready."
fi

echo "starting services"
yabai --start-service

echo "setting up mac defaults"
defaults write -g ApplePressAndHoldEnabled -bool true # enable key repeats
defaults write -g InitialKeyRepeat -int 15 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 2 # normal minimum is 2 (30 ms)

echo "cleaning up"
rm -rf /tmp/fonts
brew cleanup

echo "🎉  completed osx bootstrap"
