#!/bin/bash
set -euo pipefail

XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_CACHE_HOME="$HOME/.cache"

log=/tmp/dotfiles.log

current_dir=$(pwd)
root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"

cd $root_dir

# █▀▄ █▀█ █▀▀ █▄▀ █▀▀ █▀█
# █▄▀ █▄█ █▄▄ █░█ ██▄ █▀▄

if command -v docker &> /dev/null; then
  echo "setting up docker" | tee -a $log
  sudo groupadd -f docker
  sudo usermod -aG docker $USER

  sudo systemctl enable docker.service
  sudo systemctl enable containerd.service
  sudo systemctl start docker
fi


# █▀ █▀▀ ▀█▀ █░█ █▀█   █▀▄ █▀█ ▀█▀ █▀▀ █ █░░ █▀▀ █▀
# ▄█ ██▄ ░█░ █▄█ █▀▀   █▄▀ █▄█ ░█░ █▀░ █ █▄▄ ██▄ ▄█

echo "setting up dotfiles.." | tee -a $log
sudo rm -rf $HOME/.zshrc /etc/locale.conf /etc/locale.gen \
  /etc/pam.d/login /etc/pam.d/system-local-login /etc/zsh/zshenv \
  /etc/default/grub /etc/mkinitcpio.conf /etc/modprobe.d/nvidia.conf /etc/issue

stow --target=$HOME home
stow --target=$XDG_CONFIG_HOME config
stow --target=$HOME/.local local
sudo stow --target=/etc etc


# ▀█▀ █▀▄▀█ █░█ ▀▄▀   █▀█ █░░ █░█ █▀▀ █ █▄░█ █▀
# ░█░ █░▀░█ █▄█ █░█   █▀▀ █▄▄ █▄█ █▄█ █ █░▀█ ▄█

echo "installing tmux plugins" | tee -a $log
if [ ! -d $XDG_CONFIG_HOME/tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm $XDG_CONFIG_HOME/tmux/plugins/tpm
fi
$XDG_CONFIG_HOME/tmux/plugins/tpm/bin/install_plugins

# echo "install safebox" | tee -a $log
# if [ ! -f /usr/local/bin/safebox ]; then
  # curl -sSL https://raw.githubusercontent.com/monebag/safebox/main/scripts/install.sh | sh
# fi


# █▀▄▀█ █▀█ █▀█ █▀▀   █▀█ ▄▀█ █▀▀ █▄▀ ▄▀█ █▀▀ █▀▀ █▀
# █░▀░█ █▄█ █▀▄ ██▄   █▀▀ █▀█ █▄▄ █░█ █▀█ █▄█ ██▄ ▄█

echo "installing default rust.."
rustup default stable

rustup component add rust-analyzer


echo "installing node lts" | tee -a $log
fnm install --lts
fnm default lts-latest
[ ! -f ~/.node-version ] && echo "lts-latest" > ~/.node-version


# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄
#

echo "logging in to github" | tee -a $log
github-login

if [[ $SHELL != *"zsh" ]]; then
  command -v zsh | sudo tee -a /etc/shells
  chsh -s $(which zsh) $(whoami)
fi

./local/bin/install-nnn-plugins

cd $current_dir
echo "all done!!"

exec zsh
