export LC_ALL=en_AU.UTF-8
export LANG=en_AU.UTF-8
export EDITOR=nvim

# use vim mode in terminal
bindkey -v

# improve completion select
zstyle ':completion:*' menu select

# load completions
autoload -U compinit; compinit

source $HOME/dotfiles/zsh/aliases.zsh
source $HOME/dotfiles/zsh/plugins.zsh

# Add dotfiles bin to path
[ -d $HOME/dotfiles/bin ] && PATH="$HOME/dotfiles/bin:$PATH"
[ -d $HOME/dotfiles/node_modules/.bin ] && PATH="$HOME/dotfiles/node_modules/.bin:$PATH"

[ -d /usr/local/sbin ] && PATH="/usr/local/sbin:$PATH"
[ -d $HOME/bin ] && PATH="$HOME/bin:$PATH"
[ -d $HOME/local/bin ] && PATH="$HOME/local/bin:$PATH"

# plugins=(
#   fnm z aws rust tmux npm yarn 1password
#   git gitignore chuckcow emoji docker docker-compose
# )
#

# attach tmux when terminal starts
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  tmux attach || exec tmux new-session;
fi

# load custom config if there is any
if [ -f $HOME/.my_zshrc ]; then
  source $HOME/.my_zshrc
fi

# load fnm
[ -x "$(command -v fnm)" ] && eval "$(fnm env --use-on-cd --version-file-strategy recursive)" > /dev/null 2>&1

# add jenv to path
if which jenv > /dev/null 2>&1; then
  export PATH="$HOME/.jenv/bin:$PATH"
  eval "$(jenv init -)"
fi

if [ -d $HOME/go ]; then
  export GO111MODULE=on
  export PATH="$HOME/go/bin:$PATH"
fi

if [ -d $HOME/.cargo ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(direnv hook zsh)"
